services:
    etcd:
        image: quay.io/coreos/etcd:v3.5.0
        command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
        volumes:
            - prisma_etcd_data:/etcd
        networks:
            - internal

    minio:
        image: minio/minio:RELEASE.2020-12-03T00-03-10Z
        environment:
            MINIO_ACCESS_KEY: minioadmin
            MINIO_SECRET_KEY: minioadmin
        command: minio server /data
        volumes:
            - prisma_minio_data:/data
        networks:
            - internal

    milvus:
        image: milvusdb/milvus:v2.3.9
        command: ["milvus", "run", "standalone"]
        environment:
            ETCD_ENDPOINTS: etcd:2379
            MINIO_ADDRESS: minio:9000
        ports:
            - "19530:19530"
        depends_on:
            - etcd
            - minio
        networks:
            - internal
            - shared

networks:
    internal:
        internal: true
    shared:
        external: true

volumes:
    prisma_etcd_data:
    prisma_minio_data:
