services:
    portainer:
        image: portainer/portainer-ce:2.20.3
        command: -H unix:///var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        networks: [edge]
        labels:
            - traefik.enable=true
            - traefik.docker.network=edge
            - traefik.http.routers.portainer.rule=Host(`portainer.lvh.me`)
            - traefik.http.routers.portainer.entrypoints=web
            - traefik.http.services.portainer.loadbalancer.server.port=9000
volumes:
    portainer_data:
networks:
    edge:
        external: true
